# 1. Create a null vector of size 10 but the fifth value which is 1

In [2]:
import numpy as np
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 2. Create a vector with values ranging from 10 to 49

In [3]:
range_vector = np.arange(10, 50)
print(range_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [5]:
data = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(data)[0]
print(non_zero_indices)

[0 1 4]


# 5. Create a 10x10 array with random values and find the minimum and maximum values

In [6]:
random_array = np.random.rand(10, 10)
min_value = random_array.min()
max_value = random_array.max()
print(f"Minimum value: {min_value}, Maximum value: {max_value}")

Minimum value: 0.003308838543440329, Maximum value: 0.9976841009660526


# 6. Create a random vector of size 30 and find the mean value

In [7]:

random_vector = np.random.rand(30)
mean_value = random_vector.mean()
print(f"Mean value: {mean_value}")

Mean value: 0.48433285501022033
